Repository sendgrid/sendgrid-go, pull requests merged in 2018-10, with the labels that each got.

#269 use testify
  helpers/inbound/inbound_test.go
  helpers/mail/mail_v3_test.go
  sendgrid_test.go
Labels: difficulty: medium, status: code review request, type: community enhancement

#273 Exclude examples from go tests, Travis Job
  .travis.yml
  go.test.sh
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: bug

#277 Update README
  README.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#280 helpers/mail: add testify to new test
  helpers/mail/mail_v3_test.go
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#194 Allows users to submit rfc822 formatted email addresses
  helpers/mail/mail_v3.go
  helpers/mail/mail_v3_test.go
Labels: difficulty: hard, status: ready for deploy, type: community enhancement

#197 Make Getenv("message") parameter more professional
  USAGE.md
  examples/accesssettings/accesssettings.go
  examples/alerts/alerts.go
  examples/apikeys/apikeys.go
  examples/asm/asm.go
  examples/browsers/browsers.go
  examples/campaigns/campaigns.go
  examples/categories/categories.go
  examples/clients/clients.go
  examples/contactdb/contactdb.go
  examples/devices/devices.go
  examples/geo/geo.go
  examples/ips/ips.go
  examples/mail/mail.go
  examples/mailboxproviders/mailboxproviders.go
  examples/mailsettings/mailsettings.go
  examples/partnersettings/partnersettings.go
  examples/scopes/scopes.go
  examples/senders/senders.go
  examples/stats/stats.go
  examples/subusers/subusers.go
  examples/suppression/suppression.go
  examples/templates/templates.go
  examples/trackingsettings/trackingsettings.go
  examples/user/user.go
  examples/whitelabel/whitelabel.go
  helpers/mail/mail_v3.go
Labels: difficulty: easy, status: ready for deploy, type: community enhancement

#232 update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: difficulty: easy, status: ready for deploy, type: docs update

#238 Added Code Review to Contributing.md
  CONTRIBUTING.md
  README.md
Labels: difficulty: easy, status: ready for deploy, type: docs update

#292 fix broken link
  TROUBLESHOOTING.md
Labels: difficulty: easy, hacktoberfest, status: ready for deploy

#324 inbound: fix readme links
  helpers/inbound/README.md
Labels: status: code review request

#293 Use case directory structure
  USE_CASES.md
  use-cases/README.md
  use-cases/attachments-with-mailer-helper.md
  use-cases/attachments-without-mailer-helper.md
  use-cases/attachments.md
  use-cases/custom-args-with-mailer-helper.md
  use-cases/custom-args-without-mailer-helper.md
  use-cases/custom-args.md
  use-cases/legacy-templates-with-mailer-helper.md
  use-cases/legacy-templates-without-mailer-helper.md
  use-cases/legacy-templates.md
  use-cases/personalization-sending-single-email-single-recipient-with-cc-bcc.md
  use-cases/personalization-sending-single-email-single-recipient-with-cc.md
  use-cases/personalization-sending-single-email-single-recipient.md
  use-cases/personalization-sending-single-email-to-multiple-recipients.md
  use-cases/personalization-sending-single-email-to-single-recipients-with-multiple-cc-bcc.md
  use-cases/personalization-sending-two-emails-to-two-groups-recipients.md
  use-cases/personalization-without-helper-sending-same-email-to-multiple-recipients.md
  use-cases/personalization-without-helper-sending-single-email-single-recipient-with-cc-bcc.md
  use-cases/personalization-without-helper-sending-single-email-single-recipient-with-cc.md
  use-cases/personalization-without-helper-sending-single-email-single-recipient.md
  use-cases/personalization-without-helper-sending-single-email-to-single-recipients-with-multiple-cc-bcc.md
  use-cases/personalization-without-helper-sending-two-emails-to-two-groups-recipients.md
  use-cases/personalizations-with-mailer-helper.md
  use-cases/personalizations-without-mailer-helper.md
  use-cases/personalizations.md
  use-cases/sections-with-mailer-helper.md
  use-cases/sections-without-mailer-helper.md
  use-cases/sections.md
  use-cases/setup-domain-whitelabel.md
  use-cases/substitutions-with-mailer-helper.md
  use-cases/substitutions-without-mailer-helper.md
  use-cases/substitutions.md
  use-cases/transactional-templates-with-mailer-helper.md
  use-cases/transactional-templates-without-mailer-helper.md
  use-cases/transactional-templates.md
  use-cases/view-email-stats.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy

#243 impersonate subuser
  USAGE.md
  sendgrid.go
  sendgrid_test.go
Labels: difficulty: medium, status: ready for deploy, type: sendgrid enhancement
